export const PROJECTS_TYPES = {
  FETCH_PROJECTS_START: "projectData/FETCH_PROJECTS_START",
  FETCH_PROJECTS_SUCCESS: " projectData/FETCH_PROJECTS_SUCCESS",
  FETCH_PROJECTS_FAILED: "projectData/FETCH_PROJECTS_FAILED",
};
